apiVersion: skaffold/v2beta13
kind: Config
metadata:
  name: request-count-server
build:
  artifacts:
    - image: &imageName request-count-server
      # custom build if we want to keep `npm ci` out of the dockerfile for some reason.
      custom:
        buildCommand: touch .overrides.yaml && npm ci && docker build --tag $IMAGE .
deploy:
  helm:
    releases:
      - name: request-count-server
        chartPath: helm/request-count-server
        valuesFiles:
          - ./helm/values/values-local.yaml
          - .overrides.yaml # easier than setValueTemplates
        artifactOverrides:
          imageOverride: *imageName
        namespace: &namespace test-app
  kubectl:
    manifests:
      # Let skaffold handle the persistent volume too. Alternatively this could have been part of the helm chart.
      - volumes/pv-local.yaml
portForward:
  - resourceType: Service
    resourceName: request-count-server
    namespace: *namespace
    port: 3000
